name: 'Deploy frontend app to S3'
description: 'Deploy frontend app reusable action'
author: 'Gutenberg Technology'


inputs:
  artifact-name:
    description: 'Artifact name'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  aws-access-key-id:
    description: 'AWS access key id'
    required: true  
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  bucket-name:
    description: 'S3 bucket name'
    required: true
  cloudfront-distribution-id:
    description: 'Cloudfront distribution id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}