name: 'Deploy frontend app to S3'
description: 'Deploy frontend app reusable action'
author: 'Gutenberg Technology'


inputs:
  invalidation-path:
    type: string
    description: "Path to invalidate on CloudFront"
    default: "/*"
    required: false
  folder-to-upload:
    description: 'Folder to upload in the artifact'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  aws-access-key-id:
    description: 'AWS access key id'
    required: true  
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  aws-bucket-name:
    description: 'S3 bucket name'
    required: true
  aws-cloudfront-distribution-id:
    description: 'Cloudfront distribution id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: 'tree'
      run: pwd && tree -L 4
      shell: bash   
    
    
    - name: Deploy to S3
      uses: reggionick/s3-deploy@v4
      with:
        folder: ${{ inputs.folder-to-upload }}
        bucket: ${{ inputs.aws-bucket-name }}
        bucket-region: ${{ inputs.aws-region }}
        dist-id: ${{ inputs.aws-cloudfront-distribution-id }}
        invalidation: ${{ inputs.invalidation-path }}
        delete-removed: true
        private: true
        files-to-include: "**"